stages:
  data_ingestion:
    cmd: python src\data\data_ingestion.py
    deps:
    - .\src\data\data_ingestion.py
    outs:
    - data\raw\test.csv
    - data\raw\train.csv
    params:
    - data_ingestion.test_size
  data_preprocessing:
    cmd: python .\src\data\data_preprocessing.py
    deps:
    - .\src\data\data_preprocessing.py
    - data\raw\test.csv
    - data\raw\train.csv
    outs:
    - .\data\processed\test.csv
    - .\data\processed\train.csv
  feature_engg:
    cmd: python .\src\features\feature_engg.py
    deps:
    - .\src\features\feature_engg.py
    - data\processed\test.csv
    - data\processed\train.csv
    outs:
    - data\interim\test_bow.csv
    - data\interim\train_bow.csv
    params:
    - feature_engg.max_features
  modelling:
    cmd: python .\src\models\modelling.py
    deps:
    - .\src\models\modelling.py
    - data\interim\train_bow.csv
    outs:
    - models\random_forest_model.pkl
    params:
    - modelling.n_estimators
    - modelling.max_depth
  model_evaluation:
    cmd: python .\src\models\model_evaluation.py
    deps:
    - .\src\models\model_evaluation.py
    - data\interim\test_bow.csv
    - models\random_forest_model.pkl
    outs:
    - reports\model_evaluation.json
